# More info: https://www.r-bloggers.com/2020/10/basic-error-handing-in-r-with-trycatch/
# Stop 
method <- "VoomLimma"
 if (!(method %in% c("BMAseq", "DESeq2", "edgeR"))){
    stop("The method is unavailable. It should be either one of BMAseq, DESeq2, and edgeR.")
  }

# Trycatch
# If an error occurs during the execution of this code block, 
# the tryCatch() statement will call the error function, 
# which will print an error message that includes the message generated by the error (conditionMessage(e)) 
tryCatch({
 mdl.fit <- lmerTest::lmer(Area ~ Time + I(Time^2) + (Time + I(Time^2)|ID) + InSize + MOL15 + MGLP, data = q1_data)
}, error = function(e){
 cat("ERROR :", conditionMessage(e), "when analyzing the data.\n")
})

